name: Build and run tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.1.701"

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build integration tests
        run: |
          rustup target add wasm32-unknown-unknown
          cargo run -p builder

      - name: Run integration tests
        run: |
          cd integration-tests/TestRunner
          dotnet test
