name: Build and run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Build integration tests
      run: cargo run -p builder

    - name: Run integration tests
      run: cd integration-tests/TestRunner && dotnet test
